### ISSUE TITLE
Always returns null

### ISSUE THREAD

**Issue by clayrisser** [jonschlinkert/git-user-email#1]

**Comment by tunnckoCore** [comment]
@doowb @jonschlinkert still. I'll look on that later today.

**Comment by clayrisser** [comment]
I've been waiting a while for my pull request to be accepted.

In the meantime, you can set the version in your `package.json` to the following.

_package.json_
```json
{
  "packages": {
    "git-user-email": "git://github.com/codejamninja/git-user-email.git#npm"
  }
}
```

. . . or you can run

```sh
npm install --save git://github.com/codejamninja/git-user-email.git#npm
```

**Comment by tunnckoCore** [comment]
ooh cool.

**Comment by mikeerickson** [comment]
@jonschlinkert Any reason why this PR was never merged?  The current implementation returns null, whereas the above-referenced PR works as expected? 

@codejamninja thanks for your efforts, I will use your version until @jonschlinkert merges your PR
