### ISSUE TITLE
Does not search global .gitconfig, only local .git/config

### ISSUE THREAD

**Issue by billiegoose** [jonschlinkert/git-user-email#3]
(I believe this is a clarification to #1)

This behavior is unexpected, given that `git-user-name` ~~searches both.~~ Edit: actually... it may just search globally?

**Comment by jonschlinkert** [comment]
Want to do a pr?

**Comment by billiegoose** [comment]
... yeah I can do that. Ping me if a week goes by and I forget to. :)

**Comment by ghost** [comment]
Was this fixed? I recently encountered issues too.

**Comment by thomas-darling** [comment]
@jonschlinkert We just got bitten by this bug too.
Would it be possible to merge #4 and publish to NPM? :-)
